sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run cover
  #- npm run check-coverage # not ready to enforce this yet
  #- npm run build
after_success:
  #- npm run report-coverage # TODO figure out nice way to report this; codecov.io wanted way too many permissions
